urls:
  - name: "Ringvorlesung Sommersemester 2025 - University of Göttingen"
    url: "https://www.uni-goettingen.de/de/696100.html"
  - name: "Wikipedia - Quantum Computing"
    url: "https://en.wikipedia.org/wiki/Quantum_computing"
